// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-rMrxsnEn0b9z-AO1x-I9m8UNWe3l7Uk',
    appId: '1:41079748624:web:33a8c3add8173b3024b295',
    messagingSenderId: '41079748624',
    projectId: 'vozapp-1350a',
    authDomain: 'vozapp-1350a.firebaseapp.com',
    storageBucket: 'vozapp-1350a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCP8cH1Lr3RNWnaF_l02Q1slXgnmXHj2k',
    appId: '1:41079748624:android:802a051ff254861524b295',
    messagingSenderId: '41079748624',
    projectId: 'vozapp-1350a',
    storageBucket: 'vozapp-1350a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5zabN-JCf1ptpSjhpOMvHCUeJUxybQO8',
    appId: '1:41079748624:ios:e99e489a025da0aa24b295',
    messagingSenderId: '41079748624',
    projectId: 'vozapp-1350a',
    storageBucket: 'vozapp-1350a.firebasestorage.app',
    iosBundleId: 'com.example.vozApp',
  );
}
